### PR TITLE
simple_shell

### PR DESCRIPTION
**Pull request by Aasulayman**
Dear collab,
kindly check this code

### CODE REVIEW

**Review by ugberaeseac — CHANGES_REQUESTED** [review]
Please fix the .swp file ".d.c.swp]" in the source code. please remove it and push again

**Review by ugberaeseac — COMMENTED** [review]
Remove the .swp file and

**Comment by Aasulayman** [comment]
check this

**Review by ugberaeseac — APPROVED** [review]
Looks goof...

**Pull request merged**
